name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install web dependencies
        working-directory: web
        run: npm install

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Install API dependencies
        working-directory: api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mypy

      - name: Type-check (mypy)
        working-directory: api
        run: mypy app || true

      - name: Run tests (API)
        working-directory: api
        run: pytest -q

      - name: Build Docker images
        run: |
          docker build -t idp-api ./api
          docker build -t idp-web ./web
